### ISSUE TITLE
Scrolling in creative picks up the item

### ISSUE THREAD

**Issue by Madis0** [Siphalor/mouse-wheelie#1]
Scrolling while hovering on an item in creative inventory picks it up as a full stack.

It should either
- just scroll the creative inventory up and down
- move the item to the hotbar

MW 1.0.8, Fabric API 0.2.7 b 123, Fabric Loader 0.4.4 b 138, MC 1.14

**Comment by Siphalor** [comment]
Thanks for reporting ;)
I fixed this to use the vanilla behviour since everything else gets overly complicated.

The new jar is available on CurseForge soon or via [GitHub releases](https://github.com/Siphalor/mouse-wheelie/releases/tag/1.0.9%2B1.14).

**Comment by Madis0** [comment]
Can again reproduce on
Minecraft 1.15/1.15.1
Fabric Loader 0.7.2 b 174/b 175
Fabric API 0.4.23 b 276
MW 1.3.9/1.3.10

**Comment by Madis0** [comment]
Please reopen this bug @Siphalor.

**Comment by Siphalor** [comment]
Thanks for the reminder.
The first bug reported has reappeared lol

Gotta get this fixed again fast.

**Comment by Siphalor** [comment]
It's now really fixed (the items are now getting moved correctly 🎉)
