### ISSUE TITLE
[bug] Soring takes the armours from armour slots

### ISSUE THREAD

**Issue by has236** [Siphalor/mouse-wheelie#100]
**Version**
I am using Minecraft 1.16.3 with Fabric, the mod is 1.5.10 (1.16.3+)
**Describe the bug**
When I middle-click the inventory, it not only sort the inventory but also takes my armour(mostly leg and boots). With shift-middle-click it works fine, but with ctrl-middle-click, this bug appears again.

**Comment by FeedTheChunk** [comment]
On mine it moves the items (tools) in my hotbar and the offhand.  Very annoying bug.
