### ISSUE TITLE
[bug] Ctrl+Alt+LMB don't drop all of same items

### ISSUE THREAD

**Issue by ClemFR** [Siphalor/mouse-wheelie#102]
**Version**
1.16.4
**Describe the bug**
When I do Ctrl + Alt + LMB on a stack of items in a chest, only the stack of items my mouse points to is dropping

**To Reproduce**
1.Put multiple stack of the same item in a chest
2.Do Ctrl+Alt+LMB on one stack

**Expected behavior**
#70

**Comment by Hughp135** [comment]
Seems like this feature was intentionally removed in https://github.com/Siphalor/mouse-wheelie/commit/06621502949236c7295d2aada0b19752c66c13c3. Personally I think this was the most time-saving feature after auto crafting so am not sure why.

If there is no plan to add it back, the workaround is to stay on version 1.15.10.

**Comment by Siphalor** [comment]
To provide some context:

## The reasoning
After over a year of having this mod licensed as CC0 I decided to change the license this mod to Apache 2.0 in #99.
For this to have effect all contributors have to agree to the relicensing.
Bulk-dropping of items was contributed through pr #71.
The author of that pr didn't agree to the relicensing (which is their good right to do so), so I had to decide if I wanted to either revert that PR, keep parts of this mod as a different license (literally unmaintainable) or stop the relicensing.

## What happened
I reverted pr #71 and officially removed all of the code from that author so I could change the license of this project.

## The future
I actually really liked that feature even if I didn't really use it much myself. I'd like to reintroduce this feature at a later point but this time with original code commited under the new license.

## Notes
I'm gonna close this issue and reopen #70. Subscribe to notifications there if you want to get updated when this feature gets reimplemented.
