### ISSUE TITLE
[bug] can only scroll items into containers not out

### ISSUE THREAD

**Issue by stylinnile** [Siphalor/mouse-wheelie#104]
java 1.16.4, fabric 0.10.8-1.16.4, mousewheelie-1.6.2+mc1.16.4, windows 10
I can only use the scroll wheel to move items from my inventory to containers. I cant use the scroll wheel to move items out of any container. Scrolling up or down on an item in my inventory moves it in to the chest

mods list: 
_fabric-api-0.29.3+1.16.jar_
_modmenu-1.14.13+build.19.jar_
_mousewheelie-1.6.2+mc1.16.4.jar_
_optifabric-1.8.16.jar_
_OptiFine_1.16.4_HD_U_G5.jar_

**Expected behavior**
expected to be able to scroll items out of a container

**config file**
[https://pastebin.com/EgzRWkKc](https://pastebin.com/EgzRWkKc)

**Comment by Siphalor** [comment]
Ah, I found the issue. I failed when reimplementing the scroll inversion.
Work around until the fix is released: Disable the `invert` config in `scrolling`.

Expect a fixed release soon:tm:
