### ISSUE TITLE
[bug] 1.6.4 doesn't bundle Tweed

### ISSUE THREAD

**Issue by Madis0** [Siphalor/mouse-wheelie#106]
**Version**
Minecraft 1.16.5, MW 1.6.4
**Describe the bug**
Cannot launch the game without Tweed. Did not test with Tweed, as its CF page says mods should bundle it.

**To Reproduce**
1. Get Mouse Wheelie 1.6.4, Fabric, Fabric API
2. Start the game

**Expected behavior**
Expected Tweed to be bundled as in 1.6.3.

**Log**
I assume the picture is enough

**Additional context**
![error](https://user-images.githubusercontent.com/8611110/107082243-8ffbde80-67fc-11eb-91e4-91918920218c.png)

**Comment by Siphalor** [comment]
it works on my machine ¯\_(ツ)_/¯

But memes aside:
Can you please check which version of Fabric-Loader you are using?
And can you unzip the mouse-wheelie jar file and send the `fabric.mod.json`?

**Comment by Madis0** [comment]
Loader 0.11.1 and 

<details>

```

{
  "schemaVersion": 1,
  "id": "mousewheelie",
  "version": "1.6.4+mc1.16.4",
  "name": "Mouse Wheelie",
  "description": "Improves mouse wheel actions in some guis.",
  "authors": [
    "Siphalor"
  ],
  "contributors": [
    "Fourmisain"
  ],
  "contact": {
    "email": "modding@siphalor.de",
    "issues": "https://github.com/Siphalor/mouse-wheelie/issues",
    "sources": "https://github.com/Siphalor/mouse-wheelie"
  },
  "license": "CC0-1.0",
  "icon": "assets/mousewheelie/icon.png",
  "environment": "*",
  "mixins": [
    "mousewheelie.mixins.json"
  ],
  "entrypoints": {
    "client": [
      {
        "value": "de.siphalor.mousewheelie.client.MWClient"
      }
    ],
    "main": [
      {
        "value": "de.siphalor.mousewheelie.MouseWheelie"
      }
    ],
    "tweed:config": [
      {
        "value": "de.siphalor.mousewheelie.MWConfig"
      }
    ]
  },
  "suggests": {
    "fabric": "*"
  },
  "conflicts": {
    "appliedenergistics2": "*"
  },
  "depends": {
    "fabricloader": "\u003e\u003d0.4.0",
    "minecraft": "\u003e\u003d1.16-alpha",
    "tweed": "\u003e\u003d3.0.0-beta.11"
  },
  "custom": {
    "modmenu:clientsideOnly": true
  },
  "jars": [
    {
      "file": "META-INF/jars/fabric-api-base-0.1.3+12a8474ca7.jar"
    },
    {
      "file": "META-INF/jars/fabric-events-interaction-v0-0.3.3+7066030fa7.jar"
    },
    {
      "file": "META-INF/jars/fabric-events-lifecycle-v0-0.2.0+16acbe5ba7.jar"
    },
    {
      "file": "META-INF/jars/fabric-item-api-v1-1.0.0+16acbe5ba7.jar"
    },
    {
      "file": "META-INF/jars/fabric-lifecycle-events-v1-1.2.0+74cc3b20a7.jar"
    },
    {
      "file": "META-INF/jars/fabric-key-binding-api-v1-1.0.1+730711c6a7.jar"
    },
    {
      "file": "META-INF/jars/fabric-networking-v0-0.1.10+e00ecb5fa7.jar"
    },
    {
      "file": "META-INF/jars/fabric-tag-extensions-v0-1.0.1+35e08e33a7.jar"
    },
    {
      "file": "META-INF/jars/fabric-tool-attribute-api-v1-1.2.0+d21d4635a7.jar"
    },
    {
      "file": "META-INF/jars/fabric-resource-loader-v0-0.2.8+35e08e33a7.jar"
    },
    {
      "file": "META-INF/jars/tweed-1.16-3.0.0-beta.22.jar"
    },
    {
      "file": "META-INF/jars/amecsapi-1.16-1.1.3+mc1.16.5.jar"
    },
    {
      "file": "META-INF/jars/config-2-4.7.0-unstable.jar"
    }
  ]
}

```

</details>

Interestingly enough, I downloaded MW again (json taken from that ^) and it runs now. But on CF there is at least one person facing the same issue (check comments).

**Comment by Siphalor** [comment]
> Interestingly enough, I downloaded MW again (json taken from that ^) and it runs now. But on CF there is at least one person facing the same issue (check comments).

Yea, I saw that comment.
I actually have no clue what's going on there as I didn't change the uploaded version (not sure I was even able to do that).
Maybe it's just some CurseForge trickery going on 🤔

I'm gonna keep this open until I've got notice from the CurseForge that this is really just a corrupted download kind of thing.

**Comment by Siphalor** [comment]
After a reupload this issue seems to be resolved.
