### ISSUE TITLE
[bug] Misleading disclaimer

### ISSUE THREAD

**Issue by Madis0** [Siphalor/mouse-wheelie#107]
**Version**
N/A

**Describe the bug**
You have a disclaimer "I only maintain this site and the GitHub source site. All other websites distributing the mod are not owned/affiliated with me and might publish incorrect or outdated mod files or even worse malware." on both Curseforge and Modrinth. So which one _is_ official? 😛

**To Reproduce**
1. https://modrinth.com/mod/mouse-wheelie
2. https://www.curseforge.com/minecraft/mc-mods/mouse-wheelie

**Expected behavior**
Mention, which sites you support specifically, _this_ can refer to anything.

**Log**
N/A

**Additional context**
May be the case for your other mods too.

**Comment by Siphalor** [comment]
I'm a professional lol
