### ISSUE TITLE
Feature request: Alt-click to drop items

### ISSUE THREAD

**Issue by coldino** [Siphalor/mouse-wheelie#11]
As per the title... just like Inventory tweaks. This combined with the ability to swipe over multiple stacks makes a very quick way to empty out unwanted items.

Loving this mod so far. Just works. Love it!

**Comment by coldino** [comment]
Thanks for the quick work!

This works well for alt-swipe dropping in bulk. Could you add single clicking with alt to drop a single stack please?

Also tested auto-refill and tool picking - both work well.

**Comment by Siphalor** [comment]
Ah, I missed that. Thanks for notifying me again.
It should be fixed now.

**Comment by Madis0** [comment]
Instead of Alt, why not do use the drop key (default Q) as a modifier?
- Hover and press Q to drop one item like default
- Hold Q and click to drop the whole stack
- Hold Q and drag to drop several stacks of items

**Comment by coldino** [comment]
The drop key cannot be a modifier as it already has an action in vanilla - it drops single items repeatedly from the stack you are hovering over while you hold it.  Changing vanilla mechanics to make it drop an entire stack would be a very bad thing.

As it is, the Alt functionality mirrors the very well known and loved Inventory Tweaks behaviour (and a few clones).
