### ISSUE TITLE
[bug] Using up items in the offhand moves the mainhand item to the offhand

### ISSUE THREAD

**Issue by Siphalor** [Siphalor/mouse-wheelie#110]
**Version**
Latest

**Describe the bug**
Using up items in the offhand moves the mainhand item to the offhand.

**To Reproduce**
1. Put some fireworks in the offhand and some into the hotbar
2. Have something else in the main hand
3. Use the fireworks up
4. Observe

**Expected behavior**
The fireworks should get refilled to the offhand. The main hand should only temporarily be touched.

**Log**
N/A

**Additional context**
Originally reported by *bumble*  via Discord.

**Comment by Siphalor** [comment]
I still can't get to repoduce this.
If anyone has an easy setup for this I might have chance to catch this :/

**Comment by The-Fireplace** [comment]
I can reproduce it.
1. Open a Singleplayer world
2. Hold a pickaxe in your main hand and some torches in your off hand
3. Place torches until you run out
4. After the last torch, the pickaxe will flicker over to your off hand and back. Every time you right click after that it will flicker over and back.

I haven't messed with it enough to reproduce the pickaxe staying in the off hand, but I think that has happened some in my main survival world (I tested those steps to reproduce with just mouse wheelie to make sure it wasn't a mod conflict)
Mouse Wheelie 1.7.1+1.16.5

**Comment by Siphalor** [comment]
> I can reproduce it.

I can now reproduce it as well!

A fix is on its way :)
