### ISSUE TITLE
Slower Inventory sorting

### ISSUE THREAD

**Issue by Janik020301** [Siphalor/mouse-wheelie#116]
Greetings,
i really enjoy using your mod. It makes so many tasks easier for me. However lately a server i was playing on added an "anti-inventory-click" plugin, to countermeasure the effect of hacking clients.

I actually asked the owner, if he also has a problem with inventory sorters, which is not the case. If the mod i was using would sort more slowly, he said, he had no problem of his players using it.

So. To raise the user experience, could you maybe add an option to put a customizable delay between sorting clicks?

Thank you very much

**Comment by Siphalor** [comment]
Hi,
I'm happy to hear that you like the mod :)
I think the option you're looking for already exists - it's called "Interaction Rate" in the "General" category.

Let me know if there are any troubles with it :)

**Comment by Janik020301** [comment]
Ah, thank you. I used the version 1.6.4 still. After updating to 1.7.1 my issue is fixed.
Thank you very much again
