### ISSUE TITLE
Feature request: scroll/key to swap armor slots

### ISSUE THREAD

**Issue by Arcensoth** [Siphalor/mouse-wheelie#12]
I love this mod and keep having new ideas and I feel like this is the best place to put them. :)

Something I have yet to see any inventory management mod implement is the ability to quickly and conveniently swap armor pieces. For example, constantly swapping out elytra for chestplate and vice versa.

This could be achieved in Mouse Wheelie by using the scroll wheel to scroll-up on a piece of armor in the inventory to swap it with whatever's being worn. A key combo such as Alt+Left Click would also be useful.

**Comment by Siphalor** [comment]
This is not implemented but I'd like to notice that since some time MW has a feature where it swaps armor stacks when right-clicking with a stack in the hand.

**Comment by Arcensoth** [comment]
@Siphalor Do you think the same code/logic can be leveraged to allow hotkey swapping while the inventory screen is open? Is it worth it? Or is that another can of worms?
