### ISSUE TITLE
[bug] Pick the Correct Tool cannot be un-mapped from middle-mouse button

### ISSUE THREAD

**Issue by Tower2k** [Siphalor/mouse-wheelie#125]
**Version**
Minecraft 1.17, mousewheelie-1.7.3+mc1.17-rc1.jar

**Describe the bug**
The 'Pick the Correct Tool' control (Options -> Controls) can't be un-mapped from middle-mouse button. It will map to any other key, but will still activate with middle-mouse. And it can't be disabled with 'Reset' button, it's always active.

**To Reproduce**
1. Go to Options -> Controls, find 'Pick the Correct Tool'
2. Click 'Reset' to clear the mapping. OR map to any other key.
3. Load map with tools 
4. On hotbar have incorrect tool selected for some block.
5. Use middle-mouse button on some block.
6. The 'Pick the Correct Tool' will activate and select a tool regardless of how it's mapped.

**Expected behavior**
The 'Pick the Correct Tool' activates only for the button to which its mapped in Controls settings.

**Comment by goodideagiver** [comment]
It's a feature that can be disabled, show your config

**Comment by Tower2k** [comment]
How is it disabled? I've edited the config in several ways.  I've tried multiple combinations of key bindings.  I was able to temporarily disable middle-mouse tool picking, with complex remapping of all the related keys, but it always comes back after restart.  The overloaded middle-mouse button is a bit frustrating.

[options.txt](https://github.com/Siphalor/mouse-wheelie/files/6720407/options.txt)

**Comment by Tower2k** [comment]
How is it disabled? I've edited the config in several ways.  I've tried multiple combinations of key bindings.  I was able to temporarily disable middle-mouse tool picking, with complex remapping of all the related keys, but it always comes back after restart.  The overloaded middle-mouse button is a bit frustrating.

[options.txt](https://github.com/Siphalor/mouse-wheelie/files/6720407/options.txt)

**Comment by Tower2k** [comment]
Sorry... new to Github

**Comment by goodideagiver** [comment]
![obraz](https://user-images.githubusercontent.com/55458485/123523084-d2e22400-d6c1-11eb-859c-226fb4ff89a0.png)

**Comment by Tower2k** [comment]
The Config menu button... Thank you!
