### ISSUE TITLE
[feature request] Item depositing

### ISSUE THREAD

**Issue by Siphalor** [Siphalor/mouse-wheelie#132]
**Is your feature request related to a problem? Please describe.**
The goal of this request is to enable the player to "deposit" all items that already exist in a container from it's inventory.

**Describe the solution you'd like**
Some weird key combination and config option that allows this.

**Describe alternatives you've considered**
N/A

**Additional context**
Taken from the discord server (original request by Zealot).

**Comment by chuiu** [comment]
I just came to suggest the same thing.  Inventory tweaks did this with the space key.  Space + right click moves all items in an inventory.  Space + left click should drop all items as well.
