### ISSUE TITLE
[bug] Ctrl+Alt+Click only dropping single slot

### ISSUE THREAD

**Issue by Siphalor** [Siphalor/mouse-wheelie#133]
**Version**
1.17.x

**Describe the bug**
When using ctrl+alt+click all stacks of the item type should be dropped but only one is.

**To Reproduce**
1. Have multiple stacks of the same item in inventory
2. Ctrl+Alt+Click
3. No Profit

**Expected behavior**
All stacks of the clicked type should be dropped.

**Log**
N/A

**Additional context**
Originally reported by floppyyy on Discord.

**Comment by Dolliwyx** [comment]
The same applies with Alt+Dragging inventories, some items tend to stay when dragging in the inventory a little bit too fast

**Comment by Siphalor** [comment]
> The same applies with Alt+Dragging inventories, some items tend to stay when dragging in the inventory a little bit too fast

That's actually a different issue :)
What you're describing happens because the Minecraft event processing can't keep up with your cursor and basically only sees it at the first slot and then at the second. 
The fix for that would be to do draw a line between both event and then manually fire all slots.
I'm gonna create a new issue for that now :)

**Comment by Siphalor** [comment]
Can someone please confirm that this bug is still around?
I'm unable to reproduce it.

If noone can confirm this I'll close this in a few weeks.

**Comment by IJustWantANamePlease** [comment]
Can reproduce with mousewheelie v1.8.8+mc 1.18.2, fabric 0.14.3. Mouse wheelie is the only mod used.
It happens in both single and multiplayer.
1.8.0+mc 1.18 behaves normally on 1.18.1.
When Ctrl+Alt+Click the item stack selected is picked up, and the first item stack (kind of "top-leftest") is droppd.

**Comment by IJustWantANamePlease** [comment]
Still appears with mousewheelie v1.8.9+mc 22w17a, fabric 0.14.5. No other mods are installed.

**Comment by ofelipedidio** [comment]
I can confirm this is an issue. If I'm not mistaken, this was introduced in one of the 1.17.2 releases.

If you do it on the first item stack it works as expected, for whoever else is going through the same issue.

**Comment by IJustWantANamePlease** [comment]
> I can confirm this is an issue. If I'm not mistaken, this was introduced in one of the 1.17.2 releases.
> 
> If you do it on the first item stack it works as expected, for whoever else is going through the same issue.

umm... Do you mean 1.18.2? I don't think there is 1.17.2 for Java Edition.

**Comment by ofelipedidio** [comment]
> > I can confirm this is an issue. If I'm not mistaken, this was introduced in one of the 1.17.2 releases.
> > If you do it on the first item stack it works as expected, for whoever else is going through the same issue.
> 
> umm... Do you mean 1.18.2? I don't think there is 1.17.2 for Java Edition.

I mean 1.17.2.

I remember installing a version of the mod on 1.17.2, noticing the bug and having to downgrade it to fix the issue. Then in 1.18.2, I couldn't find a version without the bug.
