### ISSUE TITLE
[bug] Autorefil is kinda broken

### ISSUE THREAD

**Issue by pwall2222** [Siphalor/mouse-wheelie#136]
**Version**
Minecraft 1.17
Mouse Wheelie 1.7.3

**Describe the bug**
When dropping stacks of items (Ctrl+Q) continuously the auto-refill breaks and doesn't autorefil. 

**To Reproduce**
1. Fill your inventory with one type of item.
2. Start dropping with Ctrl+Q.
3. Stops refilling.

**Expected behavior**
The items keep refilling.

**Additional context**
If you drop one item before dropping the stack again it doesn't break.

**Comment by goodideagiver** [comment]
Happens to me aswell

**Comment by TheFlagen430297** [comment]
Same here

**Comment by manuelgrabowski** [comment]
Have the same issue as well in 1.18 with 1.8.0-mc1.18-pre5, I'm afraid. I tried increasing the time between actions but that didn't change anything.
