### ISSUE TITLE
[bug] Crash on config menu

### ISSUE THREAD

**Issue by foul-fortune-feline** [Siphalor/mouse-wheelie#139]
**Version**
MC v1.17.1
Fabric v0.11.6
Coat v1.0.0-beta.9
Mouse Wheelie v1.7.3-newconfig
**Describe the bug**
Upon opening the "General" subsection of the Mouse Wheelie configuration, either through the "open" button or the sidebar, minecraft crashes

**To Reproduce**
1. Open Mouse Wheelie Config
2. Click General
3. Game crashes

**Expected behavior**
General config opens

**Log**
[crash-report.log](https://github.com/Siphalor/mouse-wheelie/files/7110247/crash-report.log)

**Additional context**
None of my other configs have been throwing issues, but this is the only one using Coat instead of Cloth so that might also be the issue.

**Comment by Siphalor** [comment]
This is fixed already in the latest newconfig releases.
