### ISSUE TITLE
[bug] JEI isn't being shown from time to time

### ISSUE THREAD

**Issue by Temchar** [Siphalor/mouse-wheelie#148]
**Version**
MC:1.18    MW: 3.0.0 Alpha 2
**Describe the bug**
the JEI inventory section just stops working sometimes.

**To Reproduce**
I don't know, It just stopped working

**Expected behavior**
the JEI area to show up when i opened my inventory

**Comment by Siphalor** [comment]
Can you clearly pin this down to Mouse Wheelie?

**Comment by Temchar** [comment]
I am honestly not sure, as I don't know any steps to replicate it. The only
other mod that might be affecting it is roughly enough items.

If you want I can send you a copy of the pack I'm using

**Comment by Siphalor** [comment]
Well, Roughly Enough Items is the successor of JEI.

I really don't think that Mouse Wheelie nor its dependencies are related to your issue.
