### ISSUE TITLE
[bug] Crash upon loading the game

### ISSUE THREAD

**Issue by KirboSoftware** [Siphalor/mouse-wheelie#151]
**Version**
1.18.1
**Describe the bug**
Launching with `mousewheelie-1.8.0+mc1.18-pre5.jar` causes crash

**To Reproduce**
1. Put it in your mods folder or curseforge launcher and press launch
2. Crash report given with `java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'tweed4_base'!`

**Expected behavior**
That it wouldn't have crashed the game

**Log**
https://gist.github.com/JoostMSoftware/1e1e814cf3ca74bc1563af1cf434cb76

**Additional context**
This is in a modpack I'm working on and could be something inside my enviroment that could cause an Issue. But wanted to share in case it did had an issue

**Comment by Siphalor** [comment]
hm, that crashlog doesn't make sense at all.

Can you try deleting and downloading Mouse Wheelie again?
Sometimes CurseForge has some hiccups.

**Comment by KirboSoftware** [comment]
I removed it and reinstalled it in the modpack I'm working on and it boots just fine. I assume that curseforge has it's issues then. Apologies for making this report and have a pleasant day.

**Comment by Siphalor** [comment]
No problem.
You were completely correct reporting this :)

CurseForge gets us all from time to time with its corrupted files ^^
