### ISSUE TITLE
[bug] Mousewheelie causes a Mixin Bootstrap error (Hard-Crash)

### ISSUE THREAD

**Issue by Delfite** [Siphalor/mouse-wheelie#154]
**Version**
Minecraft Version: 1.18.1
Mod Version: mousewheelie-1.8.1+mc1.18-pre5.jar
Modloader Version: Fabric-0.13.2

**Describe the bug**
Upon launching the game with all of my mods enabled except Mouse Wheelie this crash does not occur. Upon booting up the game with only Mouse Wheelie enabled, the game will reach a white screen and stay on it for 1 second, wherein the game immediately closes and sends me straight back to the Minecraft Launcher with no Fabric error screen.

**To Reproduce**
1. Profile Settings
 -Use Fabric-0.13.2
 -Use fabric-api-0.46.4+1.18.jar
 -Use mousewheelie-1.8.1+mc1.18-pre5.jar
2. Launch the game
3. The crash should happen immediately regardless of JVM arguments since I'm only using the default ones but with 9GBs of RAM instead of the default 4GBs

**Expected behavior**
The game shouldn't have crashed, duh.

**Log**
No, you get [all of the log.](https://pastebin.com/hdErt3TS)
Don't confuse people by saying "the important parts of the log" since nobody knows what that means, it's too **_ambiguous._**

**Additional context**
This is not a mod conflict but rather an issue of _skill._

**Comment by Delfite** [comment]
All mods being disabled except for Mouse Wheelie of course
![all-disabled1](https://user-images.githubusercontent.com/23504262/154888490-5bc7975e-f590-4cf4-ae31-17f1a9a60cda.PNG)

**Comment by Siphalor** [comment]
This has already been fixed in version 1.8.2. 

I adjusted the Minecraft versions, so it should show up in the launcher as well.
