### ISSUE TITLE
[bug] Reference map could not be read

### ISSUE THREAD

**Issue by ghost** [Siphalor/mouse-wheelie#157]
**Version**
1.18.1

**Describe the bug**
this warning appears in the client latest.log on each startup 

**To Reproduce**
1. launch the game

**Expected behavior**
I expected the mod to not produce a warning log

**Log**
[16:23:28] [main/WARN]: Reference map 'coat-refmap.json' for coat.mixins.json could not be read. If this is a development environment you can ignore this message

**Comment by Siphalor** [comment]
Well this was just a really tiny thing, but it's fixed with the release for 1.18.2 - since this isn't a big issue there's no ETA for the other versions.
