### ISSUE TITLE
[bug] 

### ISSUE THREAD

**Issue by Nuzza** [Siphalor/mouse-wheelie#162]
**Version**
Minecraft: 1.18.2 Fabric
Mod: 1.8.6

**Describe the bug**
Minecraft crashes on launch with mod installed

**To Reproduce**
1. Install latest version of Mouse Wheelie (1.8.6)
2. Launch Minecraft and press Play
3. Minecraft crashes

**Expected behavior**
Minecraft launches and shows the main menu.

**Log**
Crash log:
[crash-2022-03-26_22.56.54-client.txt](https://github.com/Siphalor/mouse-wheelie/files/8355381/crash-2022-03-26_22.56.54-client.txt)

**Additional context**
Minecraft error message screenshot:
![Error Message](https://user-images.githubusercontent.com/29596317/160239551-58ee4d47-6edf-4370-9c72-c19ffdb8635c.png)

**Comment by Siphalor** [comment]
This is a duplicate to #161 and has just now been fixed in version 1.8.7.

**Comment by Nuzza** [comment]
I have confirmed that it is this mod as disabling it (using CurseForge's toggle button) and seeing if Minecraft still crashes which it does not.

**Comment by Nuzza** [comment]
Oh, ok thanks.
