### ISSUE TITLE
1.19 Snapshots

### ISSUE THREAD

**Issue by JaTiTV** [Siphalor/mouse-wheelie#164]
could you support the current snapshots?

**Comment by Siphalor** [comment]
done :)

I hope stuff works as I don't really have a lot of time right now for testing and bug hunting.

**Comment by JaTiTV** [comment]
Could you also support 22w16b since the 22w17a is very buggy?

**Comment by JaTiTV** [comment]
[crash-2022-04-30_00.02.29-client.txt](https://github.com/Siphalor/mouse-wheelie/files/8594996/crash-2022-04-30_00.02.29-client.txt)

**Comment by Siphalor** [comment]
Well, it was actually broken on both versions ^^

I fixed the issue - it should work on both now :)

**Comment by JaTiTV** [comment]
Ich teste es, danke dir :-)
