### ISSUE TITLE
1.19

### ISSUE THREAD

**Issue by JaTiTV** [Siphalor/mouse-wheelie#166]
Can you Update to 1.19?

**Comment by Siphalor** [comment]
I already did that, I just had to wait for CurseForge/Modrinth allowing me to mark the versions as 1.19 compatible ^^

Thanks for the reminder though, they should now show up correctly :smiley:

**Comment by JaTiTV** [comment]
it loads but does not work

**Comment by Siphalor** [comment]
Can you post the log?

It seems to run fine for me. You may also want to clarify what exactly is broken for you.

**Comment by JaTiTV** [comment]
here is my log: https://paste.ee/p/23l28
When I turn the mouse wheel or press the middle mouse button, nothing happens.

**Comment by JaTiTV** [comment]
I can not open the config either

**Comment by JaTiTV** [comment]
In Survival it goes. Not in Creative

**Comment by Siphalor** [comment]
If you're talking about the creative player inventory screen, then yes that's a deliberate choice.

Minecraft's implementation of that screen is quite different from basically every other inventory screen, so I chose not to support it to avoid major brain injuries ;)

I might pick that up in the future again, but I currently really don't have the time to do so.

**Comment by JaTiTV** [comment]
couldn't you solve it with an option so that you can turn it back on at your own responsibility, since i mostly play in creative and never had problems with it?
