### ISSUE TITLE
Mouse Wheelie Stops Responding on Spigot Server

### ISSUE THREAD

**Issue by EclipseofLife** [Siphalor/mouse-wheelie#169]
To reproduce:
Join spigot 1.18.2 server, wait a little while. Interact with some inventories, sort some items.
After some time, all mouse wheelie features stop working. Scroll, drag, and sort break. Sort also randomly picks up an item when used.

I have tried removing a mod that I thought was an issue, but it persists.

The issue goes away when relogging, but is still annoying.

**Comment by XavierBit** [comment]
I can confirm those glitches, playing on a 1.19 Spigot server now, but had the same problems on the 1.18 version.
It seem auto-sort chests has been totally halted on 1.19 and is broken.
I'm using the 'Fabolously Opitmized' modpack.

**Comment by Texbio** [comment]
Also having this issue, would be amazing if it was fixed. Can confirm that it is happening on paper, spigot and purpur servers. This bug happens to me sometimes when: I ctrl+left and close the inventory gui, and I ctrl+shift+left items inside the gui.

It does not fix itself when I rejoin a server and still bugs out.
It might be easier to reproduce when you set your interaction delay to a higher value.

**Comment by IAmSneak** [comment]
Also having this issue and it also doesn't work for me when i relog, only when I restart my game. However this is not exclusive to spigot servers and the same issue exists on a fabric server (even with mousewheelie installed).

**Comment by XavierBit** [comment]
I had a crash on the SMP when using Mouse Wheelie a lot, organizing some misc chest at the raid farm.
Maybe this helps?
Find my details at I.imgur.com/p42Vxq2.jpg

Crash log:
[crash-2022-07-26_16.00.25-client.txt](https://github.com/Siphalor/mouse-wheelie/files/9192636/crash-2022-07-26_16.00.25-client.txt)

And another one. I'm using the 'yeet all of the same out of my inventory' function (Ctrl + Alt clicking on an item where all the same will be thrown into fire) when crashing. Crash log here https://bytebin.lucko.me/7zIZIrVHGn

One out of three times I use it this way to bulk-throw out all the same items of my inventory, the game crashes. So it is reproduceable, at least for me.

One thing I observed is if the Ctrl clicking in chests stops working, reloading the resource packs with F3+T helps to make it work again.

**Comment by pastelneigh** [comment]
I'm having this issue too - but on a Fabric server! I found out you can temporarily fix it without restarting Minecraft by going to Mod Menu, opening the mod's Configure menu, and select Save & Close without changing any settings. This seems to restart the mod and allows you to continue using it. It's not ideal but it's better than nothing!

From what I've noticed, the issue tends to appear when trying - to quote XavierBit, to "yeet all of the same item out of my inventory". Hope this can get fixed soon! I really enjoy using this mod :)

**Comment by Siphalor** [comment]
Yes, as I, after a long time, actually played Minecraft myself again, I was able to reproduce this issue yesterday and have a rough idea what's going on.

I'll push a bunch of fixes in the next release, so we can see if it is fixed.
When the next release is published, please report back if you're stilling into issues.

Some technical context: For one reason or another, the interaction event manager gets stuck after some time.
It may be either to some multithreading issues or an exception being thrown.
Since reloading the config resets the interaction manager, @pastelneigh's workaround does indeed function.
