### ISSUE TITLE
[bug] Configuration Button Missing

### ISSUE THREAD

**Issue by mbouington** [Siphalor/mouse-wheelie#17]
I've installed fabric loader and placed the Mouse Wheelie jar in the mods folder. Mouse Wheelie is working correctly (sorting on middle-click, replacing items in empty hotbar slots, etc) but the configuration button does not appear in the inventory screen.

Versions:
Minecraft 1.14.2
fabric-loader-0.4.8+build.155-1.14.2+build.7 - fabric-loader 1.14.2
mousewheelie-1.2.2+1.14.2

I've also tried it with fabric-api-0.3.0+build.183 in the mod folder and with mousewheelie-1.2.3+1.14.3-pre2 instead of 1.2.2+1.14.2 but the configuration button still doesn't appear.

![image](https://user-images.githubusercontent.com/12885611/59382311-6a6ab900-8d2b-11e9-8d71-10374f5a0942.png)

**Comment by mbouington** [comment]
Still not getting a configuration button in the inventory screen, but I added ModMenu-1.6.2-92 and can now access Mouse Wheelie's config screen from it.

**Comment by Siphalor** [comment]
That's intentional. I don't want to clutter the inventory screens

**Comment by mbouington** [comment]
Ah ok, I was going off a screenshot posted somewhere showing a config button in the inventory (must have been from REI or another mod). It might be worth throwing a note in the mod overview saying you need another mod to make configuration changes to Mouse Wheelie.

Thanks for the great mod! Minecraft without inventory sorting is rough!
