### ISSUE TITLE
Minecraft crash in the inventory. [QUILTMC]

### ISSUE THREAD

**Issue by Lolothepro** [Siphalor/mouse-wheelie#170]
1.18.2  
mousewheelie 1.9.0

[latest.log](https://github.com/Siphalor/mouse-wheelie/files/8918848/latest.log)
[crash-2022-06-15_20.58.12-client.txt](https://github.com/Siphalor/mouse-wheelie/files/8918851/crash-2022-06-15_20.58.12-client.txt)

**Comment by Siphalor** [comment]
Fixed in 1.9.1, currently being pushed out :)
