### ISSUE TITLE
[feature request] Item scrolling supporting NBT data

### ISSUE THREAD

**Issue by JustAHuman-xD** [Siphalor/mouse-wheelie#173]
Many times when playing on minecraft servers that deal with Vanilla items with custom nbt data, i will try to scroll an item up and it will scroll the first item with the same ID, regardless of nbt. Its a small thing but can get annoying very quickly.

Make item scrolling respect nbt data, so when scrolling an item it will only scroll that which shares the same nbt.

I can't really think of any other solutions as it seems pretty straightforward.

**Comment by Siphalor** [comment]
I'm thinking about the implementation and about what use cases I have for the current behavior.

Would it make sense not to ignore damage, enchantments (probably only enchanted items, not enchanted books) and names?

Or should all nbt data be considered?

**Comment by JustAHuman-xD** [comment]
hmmm I think it you are right and it shouldn’t take in all the nbt but it should take in those main  elements, I think it’s better not to take them all in as that might remove some QOL however you could always look into making it configurable

**Comment by Siphalor** [comment]
This is now implemented with a config option to choose from:
- `NONE`: No NBT matching
- `SOME`: Matches everything except `Damage` and `Enchantments` 
- `ALL`: Matches the NBT completely

`SOME` is now the default.

Thanks for the suggestion! :tada:
