### ISSUE TITLE
Forge is not loading the mod

### ISSUE THREAD

**Issue by DanZmodMaker** [Siphalor/mouse-wheelie#18]
**Version**
Forge 1.14.2 ver 26.0.30 and mousewheelie-1.2.2+1.14.2
**Describe the bug**
Mod is not loading into Forge. Other mods are though.

Really hope you can find out whats wrong. Been looking forward to trying your mod. I have heard a lot of good things!

**Comment by Siphalor** [comment]
This mod is not designed for forge but for [Fabric](https://fabricmc.net/).
I also do not intend to backport it to forge.
