### ISSUE TITLE
[bug] Odd "drop item" behaviour after pressing alt

### ISSUE THREAD

**Issue by Madis0** [Siphalor/mouse-wheelie#19]
**Version**
MC 1.14.3, MW 1.2.4
**Describe the bug**
Two bugs related to "drop item":
- Pressing some key (possibly Alt? #11) activates a mode that drops items on inventory click, without requiring the modifier key to be held
- Dropping items changes the hotbar activated slot 

**To Reproduce**
First bug:
1. Do something with Alt (multiple modifiers held and stuck? not sure)
2. Open inventory
3. Click any item
4. The item will drop

Second bug:
1. Drop an item (any?)
2. There is a chance that the mod will activate a different hotbar slot

**Expected behavior**
Neither should happen or should have a default-off option.

**Log**
Not a crash, so I'm not sure what log you expect.

**Additional context**

1. I know about Windows' Sticky Keys feature, but I am using Linux without similar features enabled.
2. `When to pick the correct tool` is set to `NONE`

**Comment by Siphalor** [comment]
Hmmm.

Sadly I can't reproduce the first bug but I will keep it open until I can find a way to reproduce it.
Does this problem appear everytime or just random?
Are you pressing the left alt key or the right one?

The second bug is a feature which is sometimes a bit unwanted so it goes to #12.

**Comment by Madis0** [comment]
Left alt and appears randomly. Maybe it could be worked around if we could rebind it, but other than that I'm not sure.

**Comment by Madis0** [comment]
Haven't noticed it for a while.

**Comment by Siphalor** [comment]
I appreciate that ^^
