### ISSUE TITLE
[feature request] Sort option based on creative inventory

### ISSUE THREAD

**Issue by BeeFox-sys** [Siphalor/mouse-wheelie#191]
As 1.19.3 is now providing the way creative inventory is displayed through resource files rather then hard coded, would it be possible to mouse wheelie to look at those resources and sort based on them?

**Comment by Siphalor** [comment]
Thanks for the suggestion, it is already tracked in #186 though.

**Comment by BeeFox-sys** [comment]
ah! must have missed that issue! glad it's being tracked c:
