### ISSUE TITLE
1.19.3 Support

### ISSUE THREAD

**Issue by JaTiTV** [Siphalor/mouse-wheelie#192]

**Comment by Siphalor** [comment]
Already working on it :)

**Comment by JaTiTV** [comment]
no unfortunately not, when I start minecraft with the mod, then comes this error at startup [https://paste.ee/p/HG9HV](https://paste.ee/p/HG9HV)

**Comment by JaTiTV** [comment]
@Siphalor no unfortunately not, when I start minecraft with the mod, then comes this error at startup [https://paste.ee/p/HG9HV](https://paste.ee/p/HG9HV)

**Comment by Siphalor** [comment]
Well, I am working on it - so it won't work *yet*, but I'll try to get out the release as soon as it's ready.

**Comment by Siphalor** [comment]
A release supporting 1.19.3 is now published :)
