### ISSUE TITLE
[bug] No “Creative” sorting in 1.10.3 for 1.19.2

### ISSUE THREAD

**Issue by imadraude** [Siphalor/mouse-wheelie#194]
**Version**
1.19.2
**Describe the bug**
There’s no “Creative” sorting mode in config, even after deleting and recreating config file

**To Reproduce**
1. Install mod and open the game
2. Open in-game config

**Expected behavior**
Existing “Creative” sorting mode

**UPD:** installed 1.10.4, problem’s still here

**Comment by Siphalor** [comment]
The `creative` sort mode is only available for Minecraft 1.19.3.
In Minecraft 1.19.2 and below items in the creative inventory are sorted by their raw id, which is offered as the separate sort mode `raw_id`.
I have no plans to backport the creative inventory sorting to lower Minecraft versions.
