### ISSUE TITLE
[bug] Hard Crash on game launch

### ISSUE THREAD

**Issue by Delfite** [Siphalor/mouse-wheelie#195]
## **Environment**
Minecraft Version: 1.18.2
Fabric Version: 0.14.11
Mod Version: mousewheelie-1.10.5+mc1.18.2.jar

## **Describe the bug**
When I launch the game with Mouse Wheelie installed, the game crashes. Simple as that.

## **How to reproduce**
Irrelevant, the crash is specific to this instance.

## **What should have happened**
The game should've launched just fine.

## **What actually happened**
The game crashed on launch.

## **Log**
Latest.log: https://mclo.gs/nz0Far2

## **Additional context**
None. The log will tell you everything about what caused the crash.

**Comment by Siphalor** [comment]
Hi, thanks for reporting the crash.

> How to reproduce
> Irrelevant, the crash is specific to this instance.

This is never "irrelevant". Even if only you can reproduce the issue, it is important that you describe what actions lead to the crash.
Although in this case, I assume it crashed during startup without further action.

---

The log is really not helpful at all, it doesn't even contain an exception.
Please check that you uploaded the correct log or if there is really no exception in the log, please look for the crash report.

**Comment by Delfite** [comment]
> Hi, thanks for reporting the crash.
> 
> > How to reproduce
> > Irrelevant, the crash is specific to this instance.
> 
> This is never "irrelevant". Even if only you can reproduce the issue, it is important that you describe what actions lead to the crash. Although in this case, I assume it crashed during startup without further action.
> 
> The log is really not helpful at all, it doesn't even contain an exception. Please check that you uploaded the correct log or if there is really no exception in the log, please look for the crash report.

Yes, that's exactly why I said it was irrelevant, the crash happened on startup **as I had described in the initial report.**
Here's an updated crash log that still has the same issue: https://mclo.gs/MEpN7tZ
For some reason latest.log wouldn't show the same error despite it usually doing that with most crashes.
Latest.log: https://mclo.gs/Ry5f4PK

**Comment by Siphalor** [comment]
Oh, looking at the log that bug is now already tracked as #196.
It will be fixed with the next release being tested right now :)

I'm gonna close this issue, so only one version of this issue is open.
