### ISSUE TITLE
[1.19.3 Feature Request] Would be nice if scrolling wasn't changed in chest UIs

### ISSUE THREAD

**Issue by vizthex123** [Siphalor/mouse-wheelie#199]
**Is your feature request related to a problem? Please describe.**
Yes, I'm used to the NEI-style scrolling, where going up on an item in a chest sends it to your inventory (whereas you scroll down in the mod)

**Describe the solution you'd like**
A config option to change it, can be disabled by default (label it as "boomer mode" or something if ya want, lol"

I tried changing the directional scrolling option, but that doesn't do what I'd like.

**Describe alternatives you've considered**
Sadly, there isn't one :c

**Additional context**
Would be great if this got added, but at the same time I don't expect it to be. Just figured I'd suggest i.

**Comment by Siphalor** [comment]
Thanks for the suggestion.
Things like these largely depend on what one is used to and personal opinion, so I try to let anyone use the mod how they want with the config.

So I'll just add a config option to invert the scrolling :)

For the time being, you can switch the Scroll up and Scroll down keybindings in the Minecraft control settings.

**Comment by vizthex123** [comment]
awesome, i'll always take a config option over a "no lol, deal with it".

**Comment by Siphalor** [comment]
Apparently there was already a config option for that, I just completely forgot about it and took a break from modding xD

So this is already fixed ^^

**Comment by vizthex123** [comment]
nice.
