### ISSUE TITLE
[bug] Crash at start 1.18.2 Fabric

### ISSUE THREAD

**Issue by OverEarth12** [Siphalor/mouse-wheelie#203]
**Version**
Minecraft 1.18.2
Fabric 0.14.13
Fabric API 0.67.1
mousewheelie-1.10.7+mc1.18.2
**Describe the bug**
Crash at start with this mod, no other mod installed.

**To Reproduce**
1. Install lasted version of this mod along with Fabric Loader.
2. Launch the game.

**Expected behavior**
Shouldn't crash.

**Log**
[2023-02-04-1.log](https://github.com/Siphalor/mouse-wheelie/files/10608815/2023-02-04-1.log)
[crash-2023-02-04_21.07.07-client.txt](https://github.com/Siphalor/mouse-wheelie/files/10608817/crash-2023-02-04_21.07.07-client.txt)

**Comment by wildbery** [comment]
me too crashed

**Comment by mapokapo** [comment]
Having the same error.
Removing Mouse Wheelie fixes the problem.
I think it's because of a version mismatch in the embedded Amecs API mod. (it uses 1.18-pre1 instead of 1.18.2)

Edit: **Reverting Mouse Wheelie to 1.10.6 fixes the problem**.

**Comment by kittech0** [comment]
same

**Comment by pielorz** [comment]
> 1.10.6

Thanks. I had the same issue. Reverting to 1.10.6 fixed it for me too.

**Comment by Razatop** [comment]
> Reverting Mouse Wheelie to 1.10.6 fixes the problem

Careful I've been getting OpenGL Errors when exiting menus with mouse wheelie installed
