### ISSUE TITLE
Fast stock up all items of all same types into a chest

### ISSUE THREAD

**Issue by ochernyshov** [Siphalor/mouse-wheelie#209]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Please add feature to stock up items into a chest if there are same type items inside. Like press scroll with some other combination. Also 

**Describe alternatives you've considered**
Mb, another combination or button.

**Additional context**
![image](https://user-images.githubusercontent.com/61459006/226282571-8c5499b0-28d9-4c81-8de4-4e9dac5e6c1c.png)

**Comment by adrianfurgol** [comment]
You can just press Crtl + Scroll Up. And then sort afterwars using middle click. I don't see how this improvement is needed or am I missing something?

**Comment by Siphalor** [comment]
Hi, this feature has been implemented in version 1.11.0 already.

You can use it by holding space (rebindable) and scrolling up.
This will *deposit* all items that are already in the chest.

The inverse functionality can be triggered by scrolling down while over an inventory stack.
The inventory will be *restocked* with the hovered stack from the chest.
When holding shift, all items will be restocked from the chest.
