### ISSUE TITLE
Dangerous Autofill Behavior w/ Lava Bucket (and water bucket)

### ISSUE THREAD

**Issue by azerwyn** [Siphalor/mouse-wheelie#22]
There is nothing like the feeling you get when mouse wheelie auto-fills your active slot with lava and you take a hot bath because of it.  PLEASE for the love of all that possibly is... either code block lava bucket being auto-filled into a slot that was not lava bucket or provide a configuration to prevent lava buckets from ever auto-filling a slot.

I would suggest that water bucket also falls into the realm of this challenge; however, while water is generally not nearly as dangerous, it certainly can be under certain circumstances.

**Comment by azerwyn** [comment]
As an example, Eggs -> Lava Bucket.  With a stack of eggs and a lava bucket in inventory, throwing the last of the stack of eggs, after the last egg is thrown, the slot autofills with lava.

**Comment by Siphalor** [comment]
I know about a lot of refill problems so I'm going to merge this with #15.

Consider subscribing that one if there are updates on that topic.
