### ISSUE TITLE
[feature request] update to 1.20.1

### ISSUE THREAD

**Issue by qouxly** [Siphalor/mouse-wheelie#232]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
Please update the mod to 1.20.1

**Describe the solution you'd like**
that the mod is on 1.20.1 available

**Describe alternatives you've considered**
you explain me how to do it myself

**Additional context**

**Comment by michal-skraburski** [comment]
You can build it yourself! I am not familiar with mod making however the stuff inside of gradle.properties suggests you can change the minecraft version and the major version to reflect what version of minecraft to build the mod for. Note that changing this alone may not be enough, or simply fail to launch the client completely incase mojang changed something major in the client and therefore breaking the mod.
Download the code base (unstable tag) as a zip file, unzip it and edit the gradle.properties, then you can hold down shift and right click inside of explorer and select open this inside of powershell.

After changing the appropriate version fields inside of gradle.properties you can attempt building the mod from source by running ‘./gradlew build’ inside of a terminal (the powershell you opened) at that directory (assuming you’re running Windows).

If gradle manages to build this jar file successfully, I believe the mod jar file should be located under /build/libs/! Note there will be two files, and that the one you want doesn’t contain the word “sources” in it.

**Comment by qouxly** [comment]
I did it easier now, however the config screen in modmenu isn't loading so I have to change the config in the .minecraft/config  (but I don't care because it works)

**Comment by secret-pommes** [comment]
i tried to "port" it to the 1.20.1 and it not worked for me idk why i cuz idk anything about Java programming so can somebody send me his ported version ?

(would be cool 👍 )

**Comment by qouxly** [comment]
> i tried to "port" it to the 1.20.1 and it not worked for me idk why i cuz idk anything about Java programming so can somebody send me his ported version ?
> 
> (would be cool 👍 )

same, it worked first with 1.20.1 but the next day my game crashed every time I tried to sort a chest

**Comment by qouxly** [comment]
> i tried to "port" it to the 1.20.1 and it not worked for me idk why i cuz idk anything about Java programming so can somebody send me his ported version ?
> 
> (would be cool 👍 )

yeah I fixed mine today so I could send you it, if I would know how?

**Comment by secret-pommes** [comment]
> 

just mediafire or you add me on discord: not_secret1337

**Comment by michal-skraburski** [comment]
please don’t send code or built mods over mediafire as for one we all could use that code and better yet merge it into the stable branch, have a code review and see whether it is actually safe. Thanks.

**Comment by Siphalor** [comment]
There's now an official release, sorry for having to let you wait so long.
