### ISSUE TITLE
[bug] Scrolling too fast moves entire stack

### ISSUE THREAD

**Issue by Mouy07** [Siphalor/mouse-wheelie#233]
**Version**
Minecraft 1.20
Mouse Wheelie 1.11.1
**Describe the bug**
When scrolling items between inventories, scrolling too fast will move the entire stack. If I scroll fast enough it will transfer the whole stack with just two scroll wheel increments.

**To Reproduce**
1. Get a stack of items (doesn't need to be a full stack)
2. Open a chest or other inventory
3. Scroll the items quickly

**Expected behavior**
The correct number of items will be transferred (number of items = number of scroll wheel increments).

**Log**
n/a

**Additional context**
Issue is not present with Minecraft 1.19.2 Mouse Wheelie 1.10.7, but IS present with MC 1.19.2+ MW 1.11.0+. It seems that this issue was introduced in MW version 1.11.0.

**Comment by Jean-Low** [comment]
Found the same bug, I came here to open a issue but it is already oppened.
Im playing on a local hosted server, making a modpack.

**Comment by Jean-Low** [comment]
Ive instaled version 1.10.7 and it works fine.
The problem starts at version 1.11.0

**Comment by adrianfurgol** [comment]
Yes, a friend of mine and myself also observed the same behaviour. Very irritating after years of muscle memory :D 
We're playing with Minecraft 1.20.1 QuiltLoader and the fabric API installed.
I tried installing 1.10.7, but it crashes the game upon joining a world.
