### ISSUE TITLE
[bug] Server accelerated sorting doesn't work with the creative inventory

### ISSUE THREAD

**Issue by MinecraftPlayerCool** [Siphalor/mouse-wheelie#245]
**Version**
Minecraft 1.20.1 with Quilt v0.19.5
mousewheelie-1.12.2+mc1.20.1
amecs-1.3.9+mc.1.20.1

**Describe the bug**
When you try to sort your inventory, this does nothing but only works when you open a chest or an other container.

**To Reproduce**
1. Join a world in Singleplayer in creative mode
2. Open your inventory
3. Put items in your inventory
4. Try to sort your items
5. Nothing happens

**Expected behavior**
Inventory should be sorted

**Log**
I found this in the logs :

[Server thread/WARN]: Reorder inventory packet contains duplicate origin slot 0!
[Server thread/WARN]: Reorder inventory packet from player class_3222['MyPlayerName'/169, l='ServerLevel[MyWorld]', x=14.91, y=67.00, z=149.46] contains invalid data, ignoring!

**Additional context**
There is no bug when you open a chest (or an other container) and then you sort the inventory.
There is no bug in multiplayer, only in singleplayer (I tested in survival mode and creative mode too).
There is no bug when you are in survival mode.

**Comment by Siphalor** [comment]
Hi, thanks for reporting :‌)

I noticed that just the other day too - the creative inventory is code-wise always a pain to work with, so I'm actually not that surprised.
I'm having a look and see if I can get this fixed soon.
As a workaround you can disable the new "Server accelerated sorting" in the config, that will revert to the old behavior.

**Comment by MinecraftPlayerCool** [comment]
Thanks, I disabled the "server accelerated sorting" and it works perfectly !
