### ISSUE TITLE
[bug] Player is able to move even when a GUI is open

### ISSUE THREAD

**Issue by jangofett4** [Siphalor/mouse-wheelie#32]
**Version**
Minecraft 1.14.4, Fabric 1.14.4, Fabric API 0.3.0 Build 200, Mouse Wheelie 1.2.6
**Describe the bug**
Player is able to move when a GUI container is open (or chat is open).

**To Reproduce**
1. Install Fabric 1.14.4
2. Add Fabric API (build 200, older ones error when loading worlds) and Mouse Wheelie
3. Start a creative world
4. Open creative inventory and try to search a block.
5. Game tries to evaluate keys (for example: when search box is selected pressing 'e' causes inventory to close, or 'a' causes player to move left)

**Expected behavior**
Actually, nothing. Game waits for inventory button to be pressed before doing anything with player. But mouse wheelie seems to be bypassing that and directly sending keys to player.
Maybe something like 'IsModalOpen
' flag needs to be set? (I am not a mod developer, but this seems to be the case?).

**Log**
Nothing important in log.

**Additional context**
A gif showing how it works:
![mousewheelie](https://user-images.githubusercontent.com/19552452/61649368-050ad000-acba-11e9-8a28-8698b32a0f75.gif)

**Comment by Siphalor** [comment]
Already fixed :)

**Comment by jangofett4** [comment]
Sorry to re-open this issue but in which version it is fixed? Current 1.2.6 or next version that is to come?

**Comment by Siphalor** [comment]
@jangofett4 It should be fixed in version 1.2.7 which I released about two hours ago :)
I'm having a lot of hotfixes right now... 🙂
