### ISSUE TITLE
[bug] changing config files with modmenu breaks mod

### ISSUE THREAD

**Issue by cr1ssb** [Siphalor/mouse-wheelie#33]
**Version**
Minecraft 1.14.3 + 1.2.7 (latest)
**Describe the bug**
Attempted to change the configuration of the mod (specifically, how items are sorted) and upon changing the control + middle mouse click the mod didn't work at all.

**To Reproduce**
1. Change any of the general config files
2. Bug appears

**Expected behavior**
I expected the sorting method to change to the RAW_ID method.

**Log**
N/A
**Additional context**
Reloaded the game, tried both on singleplayer and multiplayer, even reinstalled the mod itself.

**Comment by Siphalor** [comment]
Is this still a thing in version 1.3.8?

**Comment by Siphalor** [comment]
I'm gonna consider this bug as gone 😎
