### ISSUE TITLE
[bug] Crash on launch 1.14.4, tweed & ClothConfig

### ISSUE THREAD

**Issue by solismaa** [Siphalor/mouse-wheelie#36]
**Version**
Minecraft 1.14.4, mouse wheelie 1.2.9 from curseforge

**Describe the bug**
Minecraft crashes on launch

**Log**
[Pastebin](https://pastebin.com/SEpTAfsE)

**Additional context**
Fixed the issue by updating [tweed](https://github.com/Siphalor/tweed-api) to 2.2.1 and [ClothConfig2](https://github.com/shedaniel/ClothConfig) to 0.4.1.
Tweed and ClothConfig2 versions bundled with mouse wheelie uses deprecated key 'requires' in fabric.mod.json, which might be the cause of the issue.

**Comment by solismaa** [comment]
I checked the tweed 2.2.1 and it also uses the 'requires' key so my first assumption wasn't the reason.

**Comment by Siphalor** [comment]
It seems like you saved me! ❤️ 

ClothConfig *silently* changed its maven repository so I never used new versions.

I'm running a few test now but possibly every other bug tracks down to the old CC version.

Thanks ❤️
