### ISSUE TITLE
[feature request] Sorting inventories better

### ISSUE THREAD

**Issue by doritobob269** [Siphalor/mouse-wheelie#41]
When sorting an inventory, if I have 2 incomplete stacks, mouse wheelie doesn't combine them into one stack if the total amount of items is <=64. The sorting also won't put a full stack of items ahead of a noncomplete stack of items, so i end up with part of a stack after a full stack. Could this be changed to combine all stacks and sort them so that the full stacks of an item are first in the order of that item in the inventory?
I'm not sure how you're handing moving items into the inventory if you're just putting items in the next available slot, but you could emulate a player shift clicking an item into the inventory to force full stacks first.

**Comment by Siphalor** [comment]
Stacking of incomplete stacks should have been working, I'm going to investigate that. 

Sort order of incomplete stacks is a known bug which I don’t really understand. 

I'm going to look into it again though.

**Comment by doritobob269** [comment]
Sweet, thanks. Yea, I don't know how hard that is to fix, but it would be much appreciated.
