### ISSUE TITLE
[feature request] Fast drop crafting

### ISSUE THREAD

**Issue by goodideagiver** [Siphalor/mouse-wheelie#43]
I think this feature would be a lifesaving addon for recently added fast crafting.

**Shortcut:** RMB+SHIF+Q or RMB+ALT+SHIFT on a crafting recipe
**Expected action:** Drops all crafted items on ground
**Example usage:** You empty a whole chest of iron ingots and craft everything into iron blocks super fast.

**Comment by Siphalor** [comment]
I really love that idea but I think it's a bit complicated so I won't touch this until I find a good and non-hacky way to handle it.

**Comment by goodideagiver** [comment]
In vanilla you can drop craft only one item per Q click, maybe you could implement a feature like macro into the mod. For example ctrl Q when hovering over a crafting result presses Q 64 times. Or even when you are doing RMB + SHIFT + Q on recipe book your mouse teleports for a split sec to the crafting result box and does the same thing as above.

**Comment by TheDeaX-Lab** [comment]
@Siphalor how get inventory and recipe in /mousewheelie/client/mixin/gui/other/MixinRecipeBookWidget.java ? I have idea

**Comment by Siphalor** [comment]
Still a bit glitchy but I'll consider this fixed
