### ISSUE TITLE
Error when trying to join server [1.14.4]

### ISSUE THREAD

**Issue by naturaGodhead** [Siphalor/mouse-wheelie#44]
I get an error when trying to join a towny server, both client and server are on 1.14.4. 

`Internal Exception: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered.`

Log: 
https://pastebin.com/d8yYsiSx

**Comment by Siphalor** [comment]
Fixed in 1.3.4 (just give curseforge a bit of time)
