### ISSUE TITLE
[Curseforge Page] Please make note of Amecs embedding

### ISSUE THREAD

**Issue by IdrisQe** [Siphalor/mouse-wheelie#46]
Due to almost never seeing it utilized, many of us, myself included, don't check the "embedded libraries" section of mod relations each time we download mods. It should be common practice to make note of any embedded libraries or other mods in the description. Especially mods that change functionality such as Amecs, which is included in Mouse Wheelie.
After I figured out an erroneous hotkey was from Amecs, I spent _far_ too long trying to figure out where the hell it had installed itself before realizing it didn't have a file at all because it was inside Mouse Wheelie.
This would have been avoided had there been some indication on the description that Amecs is included. Ideally, it would just be a Required Dependency instead of being embedded due to its nature as a mod that edits vanilla functionality, not just a library.

**Comment by Siphalor** [comment]
It needs to be embedded imo since it requires the API of Amecs. I'd like to keep the all-in-one-jar policy for Mouse Wheelie :)

The description is updated now.
