### ISSUE TITLE
[bug] Scroll factor setting is broken

### ISSUE THREAD

**Issue by Madis0** [Siphalor/mouse-wheelie#48]
What does the scroll factor actually do? 

- It doesn't seem to affect the scroll speed
- It doesn't seem to scroll more items at a time
- It doesn't seem to invert the scrollwheel behaviour (up to pull, down to push), despite the value being negative

**Comment by Siphalor** [comment]
Investigating that I noticed that I silently removed scrolling multiple stacks at once like it seems. 
Also inverting the scroll direction is really broken what I don't really understand 🤔

**Comment by Madis0** [comment]
The inversion seems to work now (1.4.0), but I still don't know what the value itself does.

**Comment by Siphalor** [comment]
The value is almost nowhere used so I think I'm gonna change it to just be an option to invert it.
I also don't see a big advantage in it having a numeric value anymore.
