### ISSUE TITLE
[bug] Middle Click ALWAYS select proper tool

### ISSUE THREAD

**Issue by nyaachen** [Siphalor/mouse-wheelie#49]
**Version**
Minecraft 1.14.4 MouseWheelie 1.3.5
**Describe the bug**
1. No matter what key you set in ModMenu or whether you select to toggle select proper tool function, When you middle click a block with any tools in hand, the proper tool is always selected first and you need to click one more time to switch to that block.
2. If you have multiple tool in your toolbar, click middle will only switch between tools and you never get the block out.

**To Reproduce**
1. prepare 1 stone, 2 diamond pickaxe, 1 diamond shovel in your hotbar.
2. in ModMenu turn off select proper tool
3. in Key Binding change the default key for MouseWheelie so that middle key does not bind anything.
4. hold the diamond shovel and middle click a stone block, you will find your main hand switches between two diamond pickaxe.

**Expected behavior**
You main hand switch to the stone block.

**Log**
N/A

**Comment by Siphalor** [comment]
It did work for weapons only lol

**Comment by nyaachen** [comment]
I find it fixed in latest version. Thx
