### ISSUE TITLE
[feature request] Include hotbar for Ctrl+click

### ISSUE THREAD

**Issue by Madis0** [Siphalor/mouse-wheelie#52]
**Is your feature request related to a problem? Please describe.**
I want to include hotbar items when Ctrl+clicking/Ctrl+scrolling items.

**Describe the solution you'd like**
An option to toggle whether hotbar is included or not.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Siphalor** [comment]
#56 lol

**Comment by Madis0** [comment]
> **An option** to toggle whether hotbar is included or not.

:stuck_out_tongue:

**Comment by Shroototem** [comment]
Not really funny when all your items go in your sorting system....

**Comment by Scubadog2000** [comment]
Having to reorganise my hotbar every time is a bit irritating, the option to turn this on and off would be much appreciated! ^^
