### ISSUE TITLE
[feature request] Item scrolling mode on modifier keypress

### ISSUE THREAD

**Issue by AgathaSorceress** [Siphalor/mouse-wheelie#53]
**Is your feature request related to a problem? Please describe.**
Currently whenever I scroll over an item in a menu with the schollwheel, the item is moved into/out of my inventory. I can hold alt to go back to the default mode.

**Describe the solution you'd like**
An option to switch to Alt-Scroll for item moving mode and just scrolling for the vanilla minecraft mode.

**Describe alternatives you've considered**
 I tried to rebind scroll up/scroll down to [shift/ctrl/alt]-scroll [up/down] but it did not work since it also triggered the modifiers.

**Additional context**
Maybe something like this? *P.S. Sorry about all the uwuified text*
![Maybe something like this?](https://i.imgur.com/JgXP0mN.png)

**Comment by Siphalor** [comment]
It's really hardcoded right now so I don't think I'll fix this anytime soon

**Comment by Siphalor** [comment]
Seems like I fixed and forgot this ages ago.
I'm gonna close it now, yay ;)
