### ISSUE TITLE
[feature request] Sort enchantment books

### ISSUE THREAD

**Issue by Madis0** [Siphalor/mouse-wheelie#54]
**Is your feature request related to a problem? Please describe.**
I would like Mouse Wheelie to sort enchantment books.

**Describe the solution you'd like**
It could sort by:

- first letter of first enchantment
- identical books (e.g. silk + prot and silk + prot)
- similar books (e.g. silk + prot and prot + mend + silk)

Same algorithm could be used for enchanted tools too, if you prefer.

**Describe alternatives you've considered**
Alternatively it could just sort by the amount of enchantments in books.

**Additional context**
N/A

**Comment by Siphalor** [comment]
Oops, that was fixed some versions ago already (was it 1.8.0?), but I forgot to close this.
