### ISSUE TITLE
[bug] Crash when scroll middle button on creative mode inventory tab

### ISSUE THREAD

**Issue by woolninesun** [Siphalor/mouse-wheelie#55]
**Version**
MultiMC pure minecraft 1.14.4 instance with following mods:
* fabric loader 0.7.4+build.177 
* fabric API 0.4.2+build.246-1.14
* Mouse Wheelie 1.3.10+1.14.4

**Describe the bug**
Crash when scroll middle button on creative mode inventory tab

**To Reproduce**
1. Run MultiMC pure minecraft 1.14.4 instance with following mods
    * fabric loader 0.7.4+build.177 
    * fabric API 0.4.2+build.246-1.14
    * Mouse Wheelie 1.3.10+1.14.4 and use default config
2. Create world or join the server
3. Open player inventory with creative mode
4. Scroll on tab (like image) with mouse middle button
![image](https://user-images.githubusercontent.com/17660894/72336924-a2d8d800-36fc-11ea-90f8-de89ed42aa5d.png)
5. crash!!

**Expected behavior**
Play game without crash for any action(?

**Log**
```
Description: Unexpected error

java.lang.NoClassDefFoundError: net/fabricmc/fabric/impl/itemgroup/CreativeGuiExtensions
	at de.siphalor.mousewheelie.client.compat.FabricCreativeGuiHelper.<init>(FabricCreativeGuiHelper.java:11)
	at net.minecraft.class_481.mouseWheelie_onMouseScrolledSpecial(class_481.java:2071)
	at de.siphalor.mousewheelie.client.ClientCore.triggerScroll(ClientCore.java:107)
	at de.siphalor.mousewheelie.client.keybinding.ScrollKeyBinding.onPressed(ScrollKeyBinding.java:22)
	at de.siphalor.amecs.impl.KeyBindingManager.onKeyPressedPriority(KeyBindingManager.java:69)
	at net.minecraft.class_312.handler$zdn000$onMouseScroll(class_312.java:550)
	at net.minecraft.class_312.method_1598(class_312.java:117)
```

**Comment by woolninesun** [comment]
[FabricCreativeGuiHelper.java](https://github.com/Siphalor/mouse-wheelie/blob/1.14/src/main/java/de/siphalor/mousewheelie/client/compat/FabricCreativeGuiHelper.java) package name need to change `itemgroup` to `item.group` base on [Add checkstyle verification for package names, fix non-API packages.](https://github.com/FabricMC/fabric/commit/28f8190f760fa03fa4f7d60fd9ee3a1b5a489608#diff-34b74349fe9ba57d883542e6708c9316)

**Comment by Siphalor** [comment]
Thanks for the hint gonna fix this soon.

Quick note why this error was a thing:
The Fabric team didn't increase the version number and because of the stupid way they handle commits without version increases my development environment still used an older iteration of the same version of that module.
I still hate them for making these nonobvious crashes a thing.

**Comment by woolninesun** [comment]
I feel much the same way on this error.
