### ISSUE TITLE
Config not loading on startup

### ISSUE THREAD

**Issue by Shroototem** [Siphalor/mouse-wheelie#57]
**Version**
Minecraft - 1.15.2
mousewheelie-1.4.0+1.15.2-pre1

**Describe the bug**
Config not loading on client restart.

**To Reproduce**
Edit config entries and restart client. Scroll direction is reverted to default.

Config as TXT file:
[mousewheelie.txt](https://github.com/Siphalor/mouse-wheelie/files/4112239/mousewheelie.txt)

**Comment by Shroototem** [comment]
Didn't have Fabric API installed... Now the config seems to be loading.

**Comment by Siphalor** [comment]
🤔 Still kind of an issue as it should even without including Fabric API on your own.
