### ISSUE TITLE
[bug][20w17a] Crash on startup with Mod Menu

### ISSUE THREAD

**Issue by supersaiyansubtlety** [Siphalor/mouse-wheelie#61]
**Version**
MC-20w17a, mousewheelie-1.4.6+mc20w17a
**Describe the bug**
Crash on startup

**To Reproduce**
Install mousewheelie and [Mod Menu](https://www.curseforge.com/minecraft/mc-mods/modmenu) on fabric for 20w17a and try to start the game

**Expected behavior**
No crash

**Log**
[crash-2020-04-23_16.05.44-client.txt](https://github.com/Siphalor/mouse-wheelie/files/4525768/crash-2020-04-23_16.05.44-client.txt)

**Additional context**
[Link to issue](https://github.com/Prospector/ModMenu/issues/109) one mod menu's repo

**Comment by Siphalor** [comment]
Fixed in 1.4.7+mc20w17a
