### ISSUE TITLE
[bug] Litematica incompat: Left Click not registering while holding shift or ctrl

### ISSUE THREAD

**Issue by MrLLobu** [Siphalor/mouse-wheelie#63]
Minecraft 1.15.2
Mod Version: 1.4.5+mc1.15.2-pre1

If you left-click while holding shift or ctrl, it sometimes wont register your left click.

It's as simple as that, i dont have any logs to paste or anything.

Edit by Siphalor:
This issue is caused by Litematica and Amecs conflicting in a strange way. I currently don't have a clue anymore why this is happening.
See maruohon/litematica#179

**Comment by Siphalor** [comment]
Thanks for letting me know :)
This issue was brought to me a whole while ago but same as now I can't reproduce it.

I'm gonna let this open but probably won't be able to fix it.

Just a thought:
What operating system are you using?

**Comment by Siphalor** [comment]
Doesn't look like it's fixed and I can totally reproduce now

Update: Only broken for the 1.15 and 1.16 versions
