### ISSUE TITLE
[feature request]Refill offhand slot

### ISSUE THREAD

**Issue by Scubadog2000** [Siphalor/mouse-wheelie#67]
The refill feature seems to be working on everything except the offhand slot.

It would be great if stacks in the offhand got refilled as they do on the hotbar, upon running out.

If I remember correctly, it was mentioned a while ago that the offhand slot poses some issues when it comes to sorting, but is there any way the refill system could work with it?

**Comment by iSneaky** [comment]
Would also love this, would be great for "fortuning ores", basically have the ores you want to fortune in your offhand, then with your fortune 3 pickaxe, hold down both left click and right click
