### ISSUE TITLE
[bug] Left Click Action Prevention issue with Litematica Installed while moving.

### ISSUE THREAD

**Issue by Ninja-Hinja42** [Siphalor/mouse-wheelie#68]
**Version**
Minecraft 1.15.2
Fabric Version 0.8.4+build.198
Mouse Wheelie 1.4.11+mc1.15.2
litematica-fabric-1.15.2-0.0.0-dev.20200515.184506

I'm on Ubuntu 20.04, not sure if that's relevant, but it also happens on Ubuntu 18.04 as well.
**Describe the bug**
While holding W, A, S, or D, with litematica installed, left clicks are frequently prevented.

**To Reproduce**
1. Install MaLiLib, Litematica, and Mouse Wheelie.
2. Go into a world and spam left click while holding w, a, s, or d.
3. Left click actions will frequently and randomly prevented.

**Expected behavior**
Left Click actions would behave normally, i.e., the player would punch every time Left Click is pressed.

**Log**
As far as i can tell, no relevant info is outputted to the log.

**Additional context**
Someone's already reported this on Litematica's page.

**Comment by Siphalor** [comment]
See #63 

The 1.14 and 1.15 versions had pulled in a dependency incorrectly, so it wasn't fixed for them. I'm working on an update.

Edit: Seems like the dep is right - no idea

Edit 2: also happening on the 1.16 version again
I will move this discussion to the old issue tho
