### ISSUE TITLE
Cannot middle-drag items in creative mode

### ISSUE THREAD

**Issue by Arcensoth** [Siphalor/mouse-wheelie#7]
**Version**
v1.1.12+1.14.2 Pre-Release 2
**Describe the bug**
Vanilla has a feature where dragging an item while holding the middle mouse button will create new stacks of the item. This mod, however, presumably attempts to sort the inventory and will disregard any items held by the cursor.

**To Reproduce**
1. Attempt to middle-drag an item in creative mode.

**Expected behavior**
New stacks of items should be created as per vanilla. Perhaps there should be a check for sorting only if there is not an item currently being held by the cursor, or only sort if the cursor is released shortly after it is pressed and/or approximately in the same position.

**Log**
Nothing in the log as this is not an error.

**Additional context**
Nothing more to add here.

**Comment by coldino** [comment]
I came here to raise the same bug - however there is a method that seems to work in all cases.

1) Drop one stack/item in the target inventory.
2) Middle-click that stack.
3) Middle-click swipe-drag over the inventory **starting on the existing stack**.

So really only a slight inconvenience.
