### ISSUE TITLE
[bug] compat issues with applied energistics 2 crafting terminals

### ISSUE THREAD

**Issue by shartte** [Siphalor/mouse-wheelie#82]
**Version**
MC 1.16.2
mousewheelie-1.5.3+mc1.16.2-pre1.jar

**Describe the bug**
Pressing middle-mouse-button in an AE2 crafting terminal will sort the hotbar into the crafting slots.

**Expected behavior**
The crafting slots of an AE2 terminal are ignored.

**Log**
No crashlog or other obvious log entries occur.

**Comment by Siphalor** [comment]
I consider this as duplicate to the more general #83
