### ISSUE TITLE
[bug] Placing the .jar file in my mods folder causes NullPointerException

### ISSUE THREAD

**Issue by jeremybuesking** [Siphalor/mouse-wheelie#85]
**Version**
1.16.2

**Describe the bug**
Once downloading the jar file and placing it in my mods folder, my forge loader fails and I get a Java null pointer exception:

The game crashed whilst rendering overlay
Error: java.lang.NullPointerException: Rendering overlay
Exit Code: -1

I have one other mod in that folder (Xaeros minimap mod) and upon removing your mod file, my launcher works fine.

**To Reproduce**
1. place .jar into mod folder, try to launch Minecraft via forge.
2. Bug appears

**Comment by Siphalor** [comment]
That's because Mouse Wheelie is a fabric mod as clearly stated on the curseforge page's title.
Fabric mods are currently incompatible with Forge.
I have currently no plans to port to Forge but I encourage anyone to go ahead and port it if they like to.

**Comment by jeremybuesking** [comment]
Gotcha. I'm new to mods and didn't realize Fabric was a thing. thanks!
