### ISSUE TITLE
[bug] Serverside mod crash on launch

### ISSUE THREAD

**Issue by Numerok** [Siphalor/mouse-wheelie#86]
**Version**
_mod_ 1.5.3+mc1.16.2-pre1 
_MC_ 1.16.2
**Describe the bug**
"Also: Armor switch if MW is installed on the server-side 🙂"
but server crashes on boot

**To Reproduce**
Start server

**Expected behavior**
Server starts correctly and Armor switch with MW works

**Log**
`Caused by: java.lang.RuntimeException: Cannot load class de.siphalor.mousewheelie.client.inventory.sort.SortMode in environment type SERVER`

**Additional context**
If described function is not existent delete entry from description in curseforge

**Comment by Siphalor** [comment]
This is a duplicate to #75 which is marked as important but I haven't really been working on it - Shame on me.

**Comment by Numerok** [comment]
Shame on me for not noticing the duplicate, but i guess it will "re-important" this bug ¯\\\_(ツ)_/¯
It's 2 months old tho

**Comment by Siphalor** [comment]
Whoops, that should be fixed in version 1.5.10
