### ISSUE TITLE
[crash] Crash with 1.14.2

### ISSUE THREAD

**Issue by Whist34** [Siphalor/mouse-wheelie#9]
**Version**
1.14.2 mousewheelie-1.1.13+1.14.2+Pre-Release+2

**Describe the bug**
1. I opened a chest in a village. Not sure what was in it. Game crashed before I could see what was inside.
2. Game client crashes with the following report.

**Log**
https://pastebin.com/nmF5fq5c

**Comment by Cynosphere** [comment]
Same crash with OptiFabric + Optifine HD F1_pre6, execpt with ANY inventory.

Honestly just needs a proper 1.14.2 release with fixed mixins more than anything.

**Comment by Siphalor** [comment]
I'm going to fix this soon but It's basically not my fault but a bug in the mixin system itself
