### ISSUE TITLE
[bug] 'Scroll creative menu' broken + slight conflict with REI

### ISSUE THREAD

**Issue by Fourmisain** [Siphalor/mouse-wheelie#92]
**Version**
1.5.7 on Minecraft 1.16.3
**Describe the bug**
'Scroll creative menu' seems to always be active and only works when scrolling in this upper region of the screen:
![scrolling-bug](https://user-images.githubusercontent.com/8464472/97096032-db7fe780-1666-11eb-8e08-dd0926d246e5.png)

Furthermore, if scrolling intensely while crossing the red region border it can enter a 'locked' state where scrolling does not work at all anymore until scrolling in the red region again.

**Expected behavior**
Scrolling outside of the Creative Menu should either always scroll the items (Vanilla behavior) when 'Scroll creative menu' is 'false' or always scroll the tabs if it is set to 'true'.

**Roughly Enough Items conflict**
Scrolling inside this small region will not scroll the recipe list but the creative tabs instead.
![scrolling-conflict](https://user-images.githubusercontent.com/8464472/97095867-5ea03e00-1665-11eb-9ce3-814d38c400da.png)

**Comment by Diablolend** [comment]
I have this bug too. This bug is very annoying.

**Comment by Fourmisain** [comment]
I'm currently working on this (fixed the bounding boxes) and I now realize that I misinterpreted 'Scroll creative menu' - I think at least.

I think it isn't meant to control the tab scrolling but instead whether you can 'scroll items' (as in move items in your inventory) or scroll the page like in vanilla when you mouseover an item.

So in short, I think this behavior is reasonable:
Scrolling outside the Creative Menu should scroll the item page (Vanilla), scrolling over the tabs should always(?) scroll the tabs and scrolling over an item should either scroll the page (Vanilla) or 'scroll the item' into your inventory, controlled via 'Scroll creative menu'.

Maybe the tab scrolling should have it's own setting as well and 'Scroll creative menu' should have a better description.
I'll probably put up a pull request for at least the fixes soon.

**Comment by Fourmisain** [comment]
Hm... while trying to add a new setting and wondering why it's not working I noticed that config changes do not save at all, even in unmodified Mouse Wheelie, apparently https://github.com/Siphalor/tweed-api/issues/3 is still an issue.

**Comment by Siphalor** [comment]
> I'm currently working on this (fixed the bounding boxes) and I now realize that I misinterpreted 'Scroll creative menu' - I think at least.
> 
> I think it isn't meant to control the tab scrolling but instead whether you can 'scroll items' (as in move items in your inventory) or scroll the page like in vanilla when you mouseover an item.
> 
> So in short, I think this behavior is reasonable:
> Scrolling outside the Creative Menu should scroll the item page (Vanilla), scrolling over the tabs should always(?) scroll the tabs and scrolling over an item should either scroll the page (Vanilla) or 'scroll the item' into your inventory, controlled via 'Scroll creative menu'.
> 
> Maybe the tab scrolling should have it's own setting as well and 'Scroll creative menu' should have a better description.
> I'll probably put up a pull request for at least the fixes soon.

I agree with this. This issue is mostly about compatibility with REI rn which I thought I already fixed (#62)

> Hm... while trying to add a new setting and wondering why it's not working I noticed that config changes do not save at all, even in unmodified Mouse Wheelie, apparently [Siphalor/tweed-api#3](https://github.com/Siphalor/tweed-api/issues/3) is still an issue.

That's really annoying as I always had trouble reproducing that issue. I hoped it vanished by itself but it doesn't look like that 😕

**Comment by Fourmisain** [comment]
I left out the config changes since I can't test them, I guess it's time to figure out what's happening with tweed.

I'm not sure how exactly to debug it, I've currently built it and changed Mouse Wheelie's build.gradle to use `compile files('../tweed-api/build/libs/tweed-3.0.0-beta.18.jar')` instead of `modImplementation` and `include`.
It's probably easier to use tweeds testmod, but I don't understand how I can build it and test with it.

**Comment by Siphalor** [comment]
hm, I'm gonna look at it as well - maybe I'm gonna be able to finally locate that bug.

About testing:

- Tweed's test mod can be used by going to run configurations in your IDE and changing the module to the testmod module.
- I also recently learned about *composite builds* in Gradle which are not supported by Loom but you can use them manually:
  - Make sure both mods use the same mappings
  - In IntelliJ go to the dependencies of your module (e.g. Mouse Wheelie)
  - Manually remove the Tweed jar
  - Then add the Tweed project as dependency and you can apparently develop both mods together
  - Repeat every time the Gradle file is reimported :/

**Comment by Siphalor** [comment]
This should be fixed thanks to Fourmisain :)

**Comment by Fourmisain** [comment]
Btw, I think that 'locked state' I experienced where scrolling had no effect may have been me scrolling on top of REI's (empty) favorite list, so that's not actually a bug.
