### ISSUE TITLE
[bug] Settings are not saved

### ISSUE THREAD

**Issue by Madis0** [Siphalor/mouse-wheelie#97]
**Version**
v1.5.9, 1.16.4
**Describe the bug**
Settings aren't saved.

**To Reproduce**
1. Open Mouse Wheelie settings
2. Toggle Treat hotbar separately
3. Test in-game
4. Restart Minecraft
5. Open Mouse Wheelie settings

**Expected behavior**
At step 3 the settings visually apply (the toggle switches), but doesn't seem to be reflected in-game. At step 5 the toggle reverts back to what it was before.

**Log**
What kind of log would help here?

**Additional context**

**Comment by Siphalor** [comment]
That's fixed in version 1.5.10 ;)
